### ISSUE TITLE
Is this a UI Framework or is this only some kind of funny thing to ?

### ISSUE THREAD

**Issue by al-sabr** [hellozee/blender-toolbox-qt#1]
If this is a framework than you should thinking about implementing in https://github.com/ocornut/imgui or make an analysis. Or you should make a proposal to the blender institute to take the UI out of only blender and make a UI framework that blender could integrate.

**Comment by hellozee** [comment]
It is just a fun project and nothing more, :smile: 
Talking about frameworks, Qt5 is the framework I used to build it. 
And at the current state, Blender is fine.
